services:
  - type: web
    name: student-success-predictor
    env: python
    buildCommand: pip install -r requirements.txt && python train_model.py
    startCommand: gunicorn app:app
    plan: free
